project_name: charm

env:
  - GO111MODULE=on
  - CGO_ENABLED=0

before:
  hooks:
    - go mod download

builds:
  - id: "charm"
    binary: "charm"
    ldflags: -s -w -X main.Version=v{{ .Version }} -X main.CommitSHA={{ .Commit }}
    goos:
      - linux
      - freebsd
      # - openbsd
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
      - "386"
      - arm
    goarm:
      - "6"
      - "7"
    ignore:
      - goos: windows
        goarch: arm64
      - goos: windows
        goarm: "6"
      - goos: windows
        goarm: "7"
      - goos: freebsd
        goarch: arm64
      - goos: freebsd
        goarch: "386"
      - goos: freebsd
        goarm: "6"
      - goos: freebsd
        goarm: "7"

dockers:
  - image_templates:
      - charmcli/charm:latest-amd64
      - charmcli/charm:{{ .Tag }}-amd64
      - charmcli/charm:v{{ .Major }}.{{ .Minor }}-amd64
      - ghcr.io/charmbracelet/charm:latest-amd64
      - ghcr.io/charmbracelet/charm:{{ .Tag }}-amd64
      - ghcr.io/charmbracelet/charm:v{{ .Major }}.{{ .Minor }}-amd64
    ids: [charm]
    goarch: amd64
    build_flag_templates:
      - --platform=linux/amd64
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description={{ .ProjectName }}
      - --label=org.opencontainers.image.url=https://github.com/charmbracelet/charm
      - --label=org.opencontainers.image.source=https://github.com/charmbracelet/charm
      - --label=org.opencontainers.image.version={{ .Tag }}
      - --label=org.opencontainers.image.created={{ .Date }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.licenses=MIT
    dockerfile: Dockerfile
    use: buildx
  - image_templates:
      - charmcli/charm:latest-arm64
      - charmcli/charm:{{ .Tag }}-arm64
      - charmcli/charm:v{{ .Major }}.{{ .Minor }}-arm64
      - ghcr.io/charmbracelet/charm:latest-arm64
      - ghcr.io/charmbracelet/charm:{{ .Tag }}-arm64
      - ghcr.io/charmbracelet/charm:v{{ .Major }}.{{ .Minor }}-arm64
    ids: [charm]
    goarch: arm64
    goarm: ""
    build_flag_templates:
      - --platform=linux/arm64/v8
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description={{ .ProjectName }}
      - --label=org.opencontainers.image.url=https://github.com/charmbracelet/charm
      - --label=org.opencontainers.image.source=https://github.com/charmbracelet/charm
      - --label=org.opencontainers.image.version={{ .Tag }}
      - --label=org.opencontainers.image.created={{ .Date }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.licenses=MIT
    dockerfile: Dockerfile
    use: buildx
  - image_templates:
      - charmcli/charm:latest-armv7
      - charmcli/charm:{{ .Tag }}-armv7
      - charmcli/charm:v{{ .Major }}.{{ .Minor }}-armv7
      - ghcr.io/charmbracelet/charm:latest-armv7
      - ghcr.io/charmbracelet/charm:{{ .Tag }}-armv7
      - ghcr.io/charmbracelet/charm:v{{ .Major }}.{{ .Minor }}-armv7
    ids: [charm]
    goarch: arm
    goarm: "7"
    build_flag_templates:
      - --platform=linux/arm32/v7
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description={{ .ProjectName }}
      - --label=org.opencontainers.image.url=https://github.com/charmbracelet/charm
      - --label=org.opencontainers.image.source=https://github.com/charmbracelet/charm
      - --label=org.opencontainers.image.version={{ .Tag }}
      - --label=org.opencontainers.image.created={{ .Date }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.licenses=MIT
    dockerfile: Dockerfile
    use: buildx

docker_manifests:
  - name_template: charmcli/charm:{{ .Tag }}
    image_templates:
      - charmcli/charm:{{ .Tag }}-amd64
      - charmcli/charm:{{ .Tag }}-arm64
      - charmcli/charm:{{ .Tag }}-armv7
  - name_template: ghcr.io/charmbracelet/charm:{{ .Tag }}
    image_templates:
      - ghcr.io/charmbracelet/charm:{{ .Tag }}-amd64
      - ghcr.io/charmbracelet/charm:{{ .Tag }}-arm64
      - ghcr.io/charmbracelet/charm:{{ .Tag }}-armv7
  - name_template: charmcli/charm:v{{ .Major }}.{{ .Minor }}
    image_templates:
      - charmcli/charm:v{{ .Major }}.{{ .Minor }}-amd64
      - charmcli/charm:v{{ .Major }}.{{ .Minor }}-arm64
      - charmcli/charm:v{{ .Major }}.{{ .Minor }}-armv7
  - name_template: ghcr.io/charmbracelet/charm:v{{ .Major }}.{{ .Minor }}
    image_templates:
      - ghcr.io/charmbracelet/charm:v{{ .Major }}.{{ .Minor }}-amd64
      - ghcr.io/charmbracelet/charm:v{{ .Major }}.{{ .Minor }}-arm64
      - ghcr.io/charmbracelet/charm:v{{ .Major }}.{{ .Minor }}-armv7
  - name_template: charmcli/charm:latest
    image_templates:
      - charmcli/charm:latest-amd64
      - charmcli/charm:latest-arm64
      - charmcli/charm:latest-armv7
  - name_template: ghcr.io/charmbracelet/charm:latest
    image_templates:
      - ghcr.io/charmbracelet/charm:latest-amd64
      - ghcr.io/charmbracelet/charm:latest-arm64
      - ghcr.io/charmbracelet/charm:latest-armv7

archives:
  - id: default
    builds:
      - charm
    format_overrides:
      - goos: windows
        format: zip
    replacements:
      windows: Windows
      darwin: Darwin
      386: i386
      amd64: x86_64

nfpms:
  - builds:
      - charm

    vendor: charmbracelet
    homepage: "https://charm.sh/"
    maintainer: "Christian Rocha <christian@charm.sh>"
    description: "Manage your Charm account and encrypt/decrypt data"
    license: MIT
    formats:
      - apk
      - deb
      - rpm
    bindir: /usr/bin

brews:
  - goarm: "6"
    tap:
      owner: charmbracelet
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    commit_author:
      name: "Christian Rocha"
      email: "christian@charm.sh"
    homepage: "https://charm.sh/"
    description: "Manage your Charm account and encrypt/decrypt data"

signs:
  - artifacts: checksum

checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  footer: |
    * * *

    Thoughts? Questions? We love hearing from you. Feel free to reach out on [Twitter](https://twitter.com/charmcli) or [The Fediverse](https://mastodon.technology/@charm).

    <a href="https://charm.sh/"><img alt="The Charm logo" src="https://stuff.charm.sh/charm-badge-unrounded.jpg" width="400"></a>
